import { generateBook } from './index.js';
import { UserInput } from './types/user-input.js';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

const sampleInput: UserInput = {
    lifeStageSegment: 'newParent',
    targetLength: 'short',
    tone: 'whimsical',
    imageStyle: 'illustrated',
    occasion: 'diwali',
    genre: 'heartfelt',
    personalityDescription: 'A warm, slightly anxious first-time dad who always double-checks the baby monitor. Loves making chai at 3am. Still getting used to London weather after 6 years.',
    funnyQuirks: 'Calls every British person "boss", pronounces Wi-Fi as "why-fy", always carries too many grocery bags in one trip.',
    memories: [
        {
            title: 'Ayaan\'s First Diwali in London',
            description: 'The first time baby Ayaan saw the lights. We dressed him in a small silk kurta. Grandmother (Dadi) was there visiting from Delhi.',
            dateRange: 'November 2025',
            people: ['Ayaan', 'Dadi', 'Pooja', 'Rahul'],
            location: 'London, UK'
        },
        {
            title: 'The Naming Ceremony (Namkaran)',
            description: 'A traditional ceremony at our home. We whispered his name in his ear. The scent of marigolds and incense filled the air.',
            people: ['Ayaan', 'Family'],
            location: 'London, UK'
        }
    ],
    characters: [
        {
            name: 'Ayaan',
            relationship: 'Son (baby)',
            keyTraits: ['curious', 'joyful', 'always grabbing things'],
            visualDescription: 'Baby with big brown eyes and a constant smile, dressed in a tiny silk kurta'
        },
        {
            name: 'Rahul',
            relationship: 'Father (protagonist)',
            keyTraits: ['warm', 'slightly anxious', 'chai-obsessed'],
            visualDescription: 'Young Indian dad, beard, warm eyes, often carrying the baby'
        },
        {
            name: 'Pooja',
            relationship: 'Mother',
            keyTraits: ['organized', 'loving', 'always singing lullabies'],
            visualDescription: 'Young Indian woman, kind face, often in comfortable ethnic wear'
        },
        {
            name: 'Dadi',
            relationship: 'Grandmother (paternal)',
            culturalBackground: 'Punjabi, Delhi-based',
            keyTraits: ['wise', 'affectionate', 'traditional'],
            visualDescription: 'Kind elder in a simple salwar kameez with reading glasses'
        }
    ],
    culturalElements: {
        primaryRegion: 'Punjab',
        festivals: ['Diwali', 'Namkaran'],
        foods: ['Gulab Jamun', 'Ladoo', 'Chai'],
        traditions: ['Kurta dressing', 'Names in ear', 'Diya lighting']
    }
};

async function testRun() {
    const startTime = Date.now();
    console.log('=== DESI TALES BOOK GENERATION ===\n');

    try {
        const result = await generateBook(sampleInput);
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        console.log(`\n\n=== GENERATION COMPLETE (${elapsed}s) ===\n`);

        const ctx = result.context;
        const lines: string[] = [];

        // If we have a polished final manuscript, use THAT as the book
        if (ctx.metadata?.finalManuscript) {
            lines.push(ctx.metadata.finalManuscript);
        } else {
            // Fallback: assemble from approved chapters
            const plan = ctx.metadata?.plan;
            lines.push(`# ${plan?.title || sampleInput.memories[0].title}`);
            if (plan?.subtitle) lines.push(`### ${plan.subtitle}`);
            lines.push('');
            lines.push(`> *Generated by Desi Tales AI • ${new Date().toLocaleDateString()}*`);
            lines.push('');
            lines.push('---');
            lines.push('');

            if (ctx.approvedChapters && ctx.approvedChapters.length > 0) {
                for (const ch of ctx.approvedChapters.sort((a, b) => a.chapterNumber - b.chapterNumber)) {
                    lines.push(`## Chapter ${ch.chapterNumber}: ${ch.title}`);
                    lines.push('');
                    lines.push(ch.content || ch.summary || '*(content not captured)*');
                    lines.push('');
                    lines.push('---');
                    lines.push('');
                }
            } else {
                // Last resort: extract from tool results
                for (const tr of result.toolResults) {
                    if (tr.name === 'generate_chapter') {
                        try {
                            const ch = JSON.parse(tr.output);
                            lines.push(`## Chapter ${ch.chapterNumber}: ${ch.title}`);
                            lines.push('');
                            lines.push(ch.content || ch.summary || tr.output);
                            lines.push('');
                            lines.push('---');
                            lines.push('');
                        } catch {
                            lines.push(tr.output);
                            lines.push('');
                        }
                    }
                }
            }
        }

        // Write the book file (clean narrative only)
        const outDir = path.join(process.cwd(), 'output');
        if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
        const outFile = path.join(outDir, `book-${Date.now()}.md`);
        fs.writeFileSync(outFile, lines.join('\n'), 'utf-8');
        console.log(`\n📖 Book written to: ${outFile}`);
        console.log(`   Chapters: ${ctx.approvedChapters?.length || 0}`);
        console.log(`   Tool calls: ${result.toolResults.length}`);
        console.log(`   Total size: ${lines.join('\n').length} chars`);

        // Write debug/audit data to a separate file
        const debugLines: string[] = ['# Desi Tales Generation Debug Log', ''];
        debugLines.push(`Generated: ${new Date().toISOString()}`);
        debugLines.push(`Duration: ${elapsed}s`);
        debugLines.push('');

        if (ctx.metadata?.culturalAudit) {
            debugLines.push('## Cultural Audit');
            debugLines.push('```json');
            debugLines.push(JSON.stringify(ctx.metadata.culturalAudit, null, 2));
            debugLines.push('```');
            debugLines.push('');
        }

        for (const tr of result.toolResults) {
            debugLines.push(`## ${tr.name}`);
            debugLines.push('```json');
            try {
                debugLines.push(JSON.stringify(JSON.parse(tr.output), null, 2));
            } catch {
                debugLines.push(tr.output.substring(0, 3000));
            }
            debugLines.push('```');
            debugLines.push('');
        }

        const debugFile = path.join(outDir, `debug-${Date.now()}.md`);
        fs.writeFileSync(debugFile, debugLines.join('\n'), 'utf-8');
        console.log(`🔍 Debug log: ${debugFile}`);

    } catch (error: any) {
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        console.error(`\nError after ${elapsed}s:`, error.message);

        if (error.state) {
            const items = error.state._generatedItems || [];
            console.log(`\nPartial results: ${items.length} items generated before error.`);

            const lines: string[] = ['# Desi Tales (Partial - Error Recovery)', ''];
            for (const item of items) {
                if (item.type === 'tool_call_output_item') {
                    const output = typeof item.output === 'string' ? item.output : JSON.stringify(item.output, null, 2);
                    lines.push(`## Tool Result`);
                    lines.push('```');
                    lines.push(output.substring(0, 5000));
                    lines.push('```');
                    lines.push('');
                }
            }

            const outDir = path.join(process.cwd(), 'output');
            if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
            const outFile = path.join(outDir, `book-partial-${Date.now()}.md`);
            fs.writeFileSync(outFile, lines.join('\n'), 'utf-8');
            console.log(`📖 Partial book written to: ${outFile}`);
        }
    }
}

testRun();
